### ISSUE TITLE
I'd use dom-augmentor module instead

### ISSUE THREAD

**Issue by WebReflection** [luwes/swiss-element#2]
The _augmentor_ is general purpose, but it has `useEffect` with empty Array that requires manual reset, or the cleaned up effects won't ever happen.

When it comes to deal with the DOM, you'd expect React like component dismount unmount life cycles for effects, and that's provided by _dom_augmentor_ module, which is just _augmentor_ but with a proper `useEffect` for the DOM world.

**Comment by WebReflection** [comment]
Actually, never mind, I've seen you have implemented your own.

**Comment by luwes** [comment]
Yup, wanted to save some bytes on that.
